Make script/setup slightly more friendly
I cloned the repo and ran the setup script as suggested on the README. I saw the following:

```
~% ./script/setup
+ brew install elixir node yarn
Warning: node-7.9.0 already installed
Warning: yarn-0.23.2 already installed
Error: elixir-1.4.0 already installed
To install this version, first `brew unlink elixir`
```

If there's already a package installed, I think we should just continue with the setup script

I removed the `set -x` from the shebang so the dependency installation output was more succinct, but stuck it back in afterwards as it's nice to see all of the output from the remaining lines